# Generated by Django 5.1.1 on 2026-09-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("schema_version", models.IntegerField(default=1)),
                ("device_id", models.CharField(max_length=64)),
                ("author", models.CharField(blank=True, max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("detection", "Обнаружение"),
                            ("unit_status", "Состояние подразделения"),
                            ("equipment_fault", "Неисправность техники"),
                            ("supply_request", "Запрос обеспечения"),
                            ("incident", "Происшествие"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("routine", "Обычный"), ("urgent", "Срочный")],
                        default="routine",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("created_at_device", models.DateTimeField()),
                ("received_at_server", models.DateTimeField(auto_now_add=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                (
                    "position_source",
                    models.CharField(
                        choices=[
                            ("gnss", "Спутник"),
                            ("manual", "Вручную"),
                            ("map", "Точка на карте"),
                            ("none", "Нет координат"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_device"],
                "indexes": [
                    models.Index(
                        fields=["received_at_server"],
                        name="reports_rep_receive_9fdf67_idx",
                    ),
                    models.Index(
                        fields=["type", "priority"], name="reports_rep_type_559114_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Фото"), ("audio", "Аудио")], max_length=16
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("declared_bytes", models.BigIntegerField(default=0)),
                ("received_bytes", models.BigIntegerField(default=0)),
                ("complete", models.BooleanField(default=False)),
                ("transcript", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
