# Generated by Django 5.1.1 on 2026-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="transcript_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("running", "Распознаётся"),
                    ("done", "Готово"),
                    ("failed", "Ошибка"),
                    ("disabled", "Распознавание выключено"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("kk", "Қазақша"),
                    ("auto", "Определять автоматически"),
                ],
                default="ru",
                max_length=8,
            ),
        ),
    ]
